# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='', max_length=200, verbose_name='Название для ссылок латиницей')),
                ('body', models.TextField(default='', verbose_name='Содержимое')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Базовая страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
