# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Картинки',
                'verbose_name': 'Картинка',
            },
        ),
    ]
