# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satori', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='body',
            field=models.TextField(default='', verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='service',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='Название для ссылок латиницей'),
        ),
    ]
