# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satori', '0005_auto_20170917_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(default='', max_length=200, verbose_name='Название для ссылок латиницей'),
        ),
    ]
