# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satori', '0006_auto_20170917_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='menuTitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок в меню'),
        ),
    ]
